In [1]:
my_name = 'Adarsh'
a = 1 
b = 10

In [2]:
print("Hello my name is {}".format(my_name))

Hello my name is Adarsh


In [3]:
type(my_name)

str

In [5]:
type(a)

int

In [6]:
isinstance(my_name,int)

False

In [7]:
isinstance(my_name,object)

True

In [8]:
a = True
b = False

In [9]:
type(a)

bool

In [10]:
a == b

False

In [11]:
a != b 

True

In [12]:
a == 1

True

In [13]:
1 < 2 

True

In [14]:
b == 0

True

In [15]:
1 < 2y 

True

In [16]:
1 <= 2 

True

In [17]:
1 < 2 < 3 

True

In [19]:
x = 2
y = 5.0
z = 2 + 1j #complex
z_alt = complex(2,1)

In [20]:
type(x)

int

In [21]:
type(y)

float

In [22]:
type(z)

complex

In [23]:
x + y

7.0

In [24]:
x * y

10.0

In [25]:
py_version = "3.11"
print("Python version {}".format(py_version))

Python version 3.11


In [26]:
language = "adarsh"

In [27]:
type(language)

str

In [28]:
language.lower()

'adarsh'

In [29]:
language.upper()

'ADARSH'

In [30]:
language.replace('sh' , 'hs')

'adarhs'

In [31]:
language

'adarsh'

In [32]:
my_list = ['red' , 'green', 'blue']
my_tuple = ('adarsh','Germany', True)

In [33]:
'red' in my_list

True

In [34]:
'adarsh' in my_tuple

True

In [35]:
for item in my_list:
    print(item)

red
green
blue


In [37]:
item = {
    'id': 123,
    'price': 19.20,
    'description': 'Book',
    'in_stock': True 
}
item

{'id': 123, 'price': 19.2, 'description': 'Book', 'in_stock': True}

In [38]:
type(item)

dict

In [39]:
item['price']

19.2

In [40]:
item['price'] = 24.9
item['price']

24.9

In [41]:
del item['in_stock']
item

{'id': 123, 'price': 24.9, 'description': 'Book'}

In [42]:
item['available'] = True
item

{'id': 123, 'price': 24.9, 'description': 'Book', 'available': True}

In [43]:
item['does_not_exist']

KeyError: 'does_not_exist'

# CUSTOM FUNCTIONS

In [44]:
def add_them(a,b):
    return a + b

In [46]:
add_them(10,112)

122

In [47]:
add_them('foo','bar')

'foobar'

In [48]:
add_them('hello',3)

TypeError: can only concatenate str (not "int") to str

# Control flow
#### Let's have a look at some control flow statements
# if/else statements
#### The if statement is used for conditional execution

In [53]:
a = 12.2
b = 1201 
if a > 0 and b > 0: 
    print("Add them! {}".format(add_them(a,b)))
elif a == 0:
    print("A is zero")
else:
    print("Nothing to see")

Add them! 1213.2


# While statements
#### you can use while loop while condition is through

In [54]:
x = 5
while x > 0:
    print(x)
    x = x - 1

5
4
3
2
1


In [55]:
for x in [1,2,3]:
    print(x)

1
2
3


In [56]:
for x in (1,2,3):
    print(x)

1
2
3


In [57]:
my_string = "ADARSH"
for i in my_string:
    print(i,end=" ")

A D A R S H 

Given a list of all products,print out the name of all the products with a price higher than 10

In [62]:
products = [
    {'name' : 'orange' , 'price' : 20},
    {'name' : 'apple' , 'price' : 8},
    {'name' : 'banana' , 'price' : 11},    
]
for item in products:
    if item['price']>10:
        print(i)

{'name': 'banana', 'price': 11}
{'name': 'banana', 'price': 11}


 ## Understanding Iterables: Sequence and Generators
 ###### Iterables anything you can iterate on
 ###### for example:
 ###### 1.sequence(tuples,lists)
 ###### 2.mappings(dictionaries) 
 ###### 3.generators

### Sequences 
###### Sequences are iterables with random access

In [65]:
record = ('Adarsh','India', True, 124) #tuple
colors = ['blue','red','green'] #list

In [66]:
for item in record:
    print(item)

Adarsh
India
True
124


In [68]:
for item in colors: 
    print(item)

blue
red
green


In [69]:
['blue','blue','red'] == ['red','blue','blue'] #order matters:


False

In [70]:
record[0] #python is zero-indexed

'Adarsh'

In [71]:
colors[2] #get the Nth item

'green'

In [72]:
colors[-1] #get the last item

'green'

## Mutable vs immutable data
#####  tuples are immutable once created they cannot be modified
##### list are mutable

In [80]:
record

('Adarsh', 'India', True, 124)

In [74]:
colors

['blue', 'red', 'green']

In [75]:
colors.append('orange')

In [76]:
colors

['blue', 'red', 'green', 'orange']

In [77]:
colors.extend(['black','white'])

In [78]:
colors

['blue', 'red', 'green', 'orange', 'black', 'white']

In [79]:
colors.extend('purple')
colors

['blue',
 'red',
 'green',
 'orange',
 'black',
 'white',
 'p',
 'u',
 'r',
 'p',
 'l',
 'e']

# Slicing lists

In [81]:
colors = ['blue','red','green','black','white']

In [82]:
colors[0:2]

['blue', 'red']

In [83]:
colors[3:4]

['black']

In [84]:
colors[:3]

['blue', 'red', 'green']

In [85]:
colors[:-1]

['blue', 'red', 'green', 'black']

# Generators
Generators are a convenient way to built iterators.
Important to remember:
1. Lazyness: values are generated on-demand
2. Lazyness: Values are not in memory
3. You can iterate only once
4. You cannot access randomly

In [92]:
# This equivalent of the built-in range() in python e
def my_range(n):
    num = 0
    while num < n:
        yield num
        num += 1

In [93]:
x = my_range(5)
x

<generator object my_range at 0x00000208BEB90790>

In [95]:
for item in x:
    print(item,end=" ")

1 2 3 4 

In [96]:
for item in x:
    print(item)

In [97]:
import sys

In [98]:
sys.getsizeof(my_range(5))

200

In [99]:
sys.getsizeof(list(my_range(5)))

120

In [100]:
sys.getsizeof(my_range(1000))

200

In [101]:
sys.getsizeof(list(my_range(1000)))

8856

# List comprehensions and Functional Programming Concepts
1. List comprehension 
2. More on generators
3. map()/reduce()/filte()

## List comprehensions
A comprehensions is a construct that allows sequences to be built from other sequences

In [104]:
squares = []
for x in range(100):
    squares.append(x*x)

In [105]:
squares

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [106]:
squares = [x*x for x in range(100)]

In [107]:
squares

[0,
 1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801]

In [108]:
combos = []
for x in [1,2,3]:
    for y in [1,2,3]:
        if x != y:
            combos.append( (x,y) )
combos

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

In [109]:
combos = [(x,y) for x in [1,2,3] for y in [1,2,3] if x != y]
combos

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

In [110]:
combos = [(x,y) for x in [1,2,3]
                for y in [1,2,3]
                if x != y]
combos

[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]

# Dictionary comprehension

In [111]:
words = "The quick brown for jumped over the lazy dog".split()
words

['The', 'quick', 'brown', 'for', 'jumped', 'over', 'the', 'lazy', 'dog']

In [113]:
word_len = {}
for w in words:
    word_len[w] = len(w)
word_len

{'The': 3,
 'quick': 5,
 'brown': 5,
 'for': 3,
 'jumped': 6,
 'over': 4,
 'the': 3,
 'lazy': 4,
 'dog': 3}

In [114]:
word_len = {w: len(w) for w in words}
word_len

{'The': 3,
 'quick': 5,
 'brown': 5,
 'for': 3,
 'jumped': 6,
 'over': 4,
 'the': 3,
 'lazy': 4,
 'dog': 3}

# Back to generators
we can define a generator using the comprehension syntax

In [115]:
squares = (x*x for x in range(10))
squares

<generator object <genexpr> at 0x00000208C0E624D0>

In [116]:
for item in squares:
    print(item,end=" ")

0 1 4 9 16 25 36 49 64 81 

# map,reduce and filter

In [117]:
# map() example
def f(x):
    return x*x

numbers = range(10)

#squares = (f(x) for x in numbers)
squares = map(f, numbers)
squares

In [118]:
list(squares)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [119]:
# map() over multiple sequences
def add_them(a,b):
    return a  + b
seq_a = [2,4,6]
seq_b = [1,2,3]

results = map(add_them, seq_a,seq_b)
list(results)

[3, 6, 9]

In [120]:
#reduce examples
from functools import reduce
seq = [1,2,3,4]
results = reduce(add_them,seq)
results

10

In [121]:
# filter() example 
def is_even(x):
    return x % 2 == 0
seq = range(10)
even_numbers = filter(is_even,seq)
list(even_numbers)

[0, 2, 4, 6, 8]

In [122]:
seq = range(10)
even_numbers = ( x for x in seq if is_even(x))
list(even_numbers)

[0, 2, 4, 6, 8]

# Dates and times
Dates and times can be tricky because there are many ways to represent them.
## Datetime objects

In [123]:
"2017-02-01" == "01/02/2017"

False

In [124]:
from datetime import datetime
some_day = datetime(2017, 2, 1, 16, 30)

In [125]:
some_day

datetime.datetime(2017, 2, 1, 16, 30)

In [126]:
some_day.strftime("%Y-%m-%d %H:%M:%S")

'2017-02-01 16:30:00'

In [127]:
d1 = datetime.strptime("2017-02-01","%Y-%m-%d")
d2 = datetime.strptime("01/02/2017", "%d/%m/%Y")
d1 == d2

True

Recap

1. strftime() for object-to-string
2. strptime() for string-to-object

In [128]:
#Timezone name
some_day.strftime("%Z")

''

In [130]:
#UTC offset
some_day.strftime("%z")

''

In [131]:
some_day.year, some_day.month, some_day.day

(2017, 2, 1)

In [132]:
some_day.hour, some_day.minute, some_day.second, some_day.microsecond

(16, 30, 0, 0)

In [133]:
some_day.tzinfo

### More on timezones
Navie datetime objects don't consider time zones
Aware datetime objects do consider time zones

In [134]:
from datetime import tzinfo, timedelta

class UTCO(tzinfo):
    def utcoffset(self, dt):
        return timedelta(hours=0)
    def dst(self, dt):
        return timedelta(0)
    def tzname(self,dt):
        return "Europe/London"
class GMT1(tzinfo):
    def utcoffset(self,dt):
        return timedelta(hours=1)
    def dst(self, dt):
        return timedelta(0)
    def tzname(self,dt):
        return "Europe/Amsterdam"

some_day = datetime(2017, 2, 1,16,30,0, tzinfo=GMT1())
another_day = datetime (2017, 2, 1, 15,30 ,0, tzinfo=UTCO())
some_day == another_day

True

In [136]:
some_day.isoformat()

'2017-02-01T16:30:00+01:00'

### Operations on dates
timedelta objects represents durations of time
This allow to perform arithemetic of dates

In [138]:
from datetime import timedelta
new_day = some_day + timedelta(days = 1)

In [139]:
some_day.strftime("%Y-%m-%d")

'2017-02-01'

In [140]:
new_day.strftime("%Y-%m-%d")

'2017-02-02'

In [142]:
some_day < new_day

True

### Simple time objects
time.time() objects represent a time of the day,independent from any particular day

In [143]:
from time import time
t0 = time()
for x in range(1000000):
    a = x
t1 = time()
t1 - t0

0.056409597396850586

# Accessing raw data
In this video, we'll discuss some common file format and how we can access data from python

### Opening and reading files

In [146]:
cat some_file.txt

SyntaxError: invalid syntax (2683662159.py, line 1)

In [147]:
file = open("some_file.txt","r")
print(file.read())

Some fiel 
this is a samlpe 
sdu and we na 
ads


In [149]:
fname = 'some_file.txt'
f = open(fname,'r')
content = f.read()
f.close()
print(content)

Some fiel 
this is a samlpe 
sdu and we na 
ads


In [150]:
fname = 'some_file.txt'
with open(fname,'r') as f:
    content  = f.read()
print(content)

Some fiel 
this is a samlpe 
sdu and we na 
ads


In [151]:
fname = 'some_file.txt'
with open(fname, 'r') as f:
    content = f.readlines()
print(content)

['Some fiel \n', 'this is a samlpe \n', 'sdu and we na \n', 'ads']


In [152]:
fname = 'some_file.txt'
with open(fname,'r') as f:
    for line in f:
        print(line)

Some fiel 

this is a samlpe 

sdu and we na 

ads


In [153]:
fname = 'some_file.txt'
with open(fname,'r') as f:
    for i,line in enumerate(f):
        print("Line {}: {}".format(i,line.strip()))

Line 0: Some fiel
Line 1: this is a samlpe
Line 2: sdu and we na
Line 3: ads


### csv files
Comma Separated values
This format is very common for import/export for spreadsheets and databases

In [154]:
%cat empdata.csv

UsageError: Line magic function `%cat` not found.


In [156]:
import csv

fname = 'empdata.csv'
with open(fname, 'r') as f:
        data_reader = csv.reader(f, delimiter=',')
        headers = next(data_reader)
        print("Headers = {}".format(headers))
        for line in data_reader:
            print(line)

Headers = ['empid', 'ename', 'sal', 'doj']
['1001', 'Ganesh Rao', '10000', '10-10-2000']
['1002', 'Anil Kumar', '23000.5', '3-3-2002']
['1003', 'Gaurav Gupta', '18000.33', '3-3-2002']
['1004', 'Hema Chandra', '16500.5', '3-3-2002']
['1005', 'Laxmi Prasanna', '12000.75', '10-8-2000']
['1006', 'Anant Nag', '9999.99', '9-9-1999']


In [157]:
fname = 'empdata.csv'
with open(fname, 'r') as f:
    data_reader = csv.reader(f, delimiter=',')
    for line in data_reader:
        print(line)

['empid', 'ename', 'sal', 'doj']
['1001', 'Ganesh Rao', '10000', '10-10-2000']
['1002', 'Anil Kumar', '23000.5', '3-3-2002']
['1003', 'Gaurav Gupta', '18000.33', '3-3-2002']
['1004', 'Hema Chandra', '16500.5', '3-3-2002']
['1005', 'Laxmi Prasanna', '12000.75', '10-8-2000']
['1006', 'Anant Nag', '9999.99', '9-9-1999']


In [159]:
fname = 'empdata.csv'
with open(fname,'r') as f:
    data_reader = csv.reader(f , delimiter=',')
    headers = next(data_reader)
    data = []
    for line in data_reader:
        item = {headers[i]: value for i, value in enumerate(line)}
        data.append(item)
data

[{'empid': '1001', 'ename': 'Ganesh Rao', 'sal': '10000', 'doj': '10-10-2000'},
 {'empid': '1002', 'ename': 'Anil Kumar', 'sal': '23000.5', 'doj': '3-3-2002'},
 {'empid': '1003',
  'ename': 'Gaurav Gupta',
  'sal': '18000.33',
  'doj': '3-3-2002'},
 {'empid': '1004',
  'ename': 'Hema Chandra',
  'sal': '16500.5',
  'doj': '3-3-2002'},
 {'empid': '1005',
  'ename': 'Laxmi Prasanna',
  'sal': '12000.75',
  'doj': '10-8-2000'},
 {'empid': '1006', 'ename': 'Anant Nag', 'sal': '9999.99', 'doj': '9-9-1999'}]

In [165]:
import json
fname = 'ProductJson.json'
with open(fname,'r') as f:
    content = f.read()
    product = json.loads(content)
product

{'Product': 'Alice Mutton', 'Customer': 'ANTON', 'Qtr 2': '$702.00'}

In [166]:
import json
fname = 'ProductJson.json'
with open(fname,'r') as f:
    product_alt = json.load(f)

In [168]:
product == product_alt

True

In [169]:
print(json.dumps(product, indent=4))

{
    "Product": "Alice Mutton",
    "Customer": "ANTON",
    "Qtr 2": "$702.00"
}


In [174]:
import json

fname = 'ProductJson.json'
with open(fname,'r') as f:
        product = json.loads(content)
        print(product['Customer'])
       
    

ANTON


### Pickles: Python object serialization

In [175]:
with open('ProductJson.json', 'r') as f:
    content = f.read()
    data = json.loads(content)
data

{'Product': 'Alice Mutton', 'Customer': 'ANTON', 'Qtr 2': '$702.00'}

In [176]:
type(data)

dict

In [185]:
import pickle

with open('data.pickle', 'wb') as f:
     pickle.dump(data,f)


In [179]:
%cat data.pickle

UsageError: Line magic function `%cat` not found.


In [180]:
import pickle

with open('data.pickle','rb') as f:
    data = pickle.load(f)
data

{'Product': 'Alice Mutton', 'Customer': 'ANTON', 'Qtr 2': '$702.00'}

In [181]:
type(data)

dict

### Creating Numpy Arrays
Numpy is the core library computing in python
This section is about the ndarray data structure

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]
x = np.array(my_list)
x

array([1, 2, 3, 4])

In [3]:
type(x)

numpy.ndarray

In [4]:
x = np.array([1,2,3,4])

In [5]:
x

array([1, 2, 3, 4])

### Multidimensional arrays

In [6]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x.size #gives the number of elements in mdarray

6

In [10]:
x.shape # gives the rows and columns 

(2, 3)

In [13]:
x.ndim  #gives the dimension of the array

2

In [16]:
x.dtype #returns the data type of the array

dtype('int32')

In [17]:
x = np.array([[1,2,3],[4,5,6]], dtype="float") # taking dtype as a flaot

In [18]:
x.dtype

dtype('float64')

In [19]:
y = x.astype('int') #converting float into int
y

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
y.dtype

dtype('int32')

### Built-in functions for creating array

In [21]:
x = np.zeros((3,2)) #creates the array 3 rows and 2 columns by filling zeros
x 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
x = np.eye(4) # main daigonal with 1 
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
x = np.diag([1,2,3]) #we can pass values for main daigonal using this
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
x = np.arange(0,10) #single dimensional array for range
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x = np.arange(0,20,2) #stepsize is two for this
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
x = np.linspace(0,3,7) #linear space to cut it down in 7 parts

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [30]:
len(x)

7

In [31]:
[1,2] * 3 #repetion of single dimensional array

[1, 2, 1, 2, 1, 2]

In [32]:
x = np.array([1,2] * 3)
x

array([1, 2, 1, 2, 1, 2])

In [34]:
x = np.repeat([1,2], 3)
x

array([1, 1, 1, 2, 2, 2])

### Stacking

In [35]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
twos = ones * 2
twos

array([[2., 2., 2.],
       [2., 2., 2.]])

In [37]:
x = np.vstack([ones , twos]) #Vertical stacking
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [38]:
x = np.hstack([twos , ones]) #horizontal stacking
x

array([[2., 2., 2., 1., 1., 1.],
       [2., 2., 2., 1., 1., 1.]])

### Basic Stats and Linear Algebra

In [48]:
x = np.array([1,2,3])
y = np.array([6,4,2])

##### Basic arithmetic operations

In [49]:
x + y

array([7, 6, 5])

In [50]:
x - y

array([-5, -2,  1])

In [51]:
x * y 

array([6, 8, 6])

In [52]:
x / y

array([0.16666667, 0.5       , 1.5       ])

In [53]:
x * 2

array([2, 4, 6])

In [54]:
y + 1

array([7, 5, 3])

In [55]:
x / 0

C:\Users\adars\AppData\Local\Temp\ipykernel_8476\3814715862.py:1: RuntimeWarning: divide by zero encountered in divide
  x / 0


array([inf, inf, inf])

In [56]:
x.sum()

6

In [57]:
w = np.array([[1,2],[3,4]])
z = np.array([[5,6],[7,8]])

In [58]:
z

array([[5, 6],
       [7, 8]])

In [59]:
z.sum()

26

In [60]:
w + z

array([[ 6,  8],
       [10, 12]])

In [61]:
w * 2

array([[2, 4],
       [6, 8]])

### Basic stats

In [62]:
x

array([1, 2, 3])

In [63]:
x.min()

1

In [64]:
x.max()

3

In [65]:
x.mean()

2.0

In [66]:
x.var()

0.6666666666666666

In [67]:
x.std()

0.816496580927726

In [68]:
x

array([1, 2, 3])

In [69]:
x.argmin()

0

In [71]:
x[x.argmin()] == x.min()

True

In [72]:
x.argmax()

2

### Matrices and lineat algebra

In [73]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
A.shape

(2, 3)

In [75]:
A.mean()

3.5

In [76]:
A.max()

6

In [77]:
A.argmax()

5

### Transpose
Switch rows and columns

In [78]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
B.shape

(3, 2)

In [83]:
C = np.random.randint(0,10, (2,3)) #create a array with 2 rows and 3 ocolumns aand inserts it in random manner from 0-100
C

array([[2, 2, 3],
       [7, 4, 5]])

In [84]:
C.shape

(2, 3)

In [85]:
A + B #GIVES ERROR BECUASE SHAPE IS NOT SAME

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [86]:
A + C

array([[ 3,  4,  6],
       [11,  9, 11]])

### Dot-product
The dot product requires the matrices to be aligned
e.g A.shape = 2*3, B.shape = 3*2 output 2*2

In [87]:
np.dot(A, B)

array([[14, 32],
       [32, 77]])

In [89]:
np.dot(A, C) #NUMBER OF ROWS SHOULD MATCH WOTH COLUMNS OF OTHER MATRICES

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

### Reshaping,indexing,slicing of arrays

#### Reshaping

In [90]:
x = np.array([1,2,3,4,5,6])
x.resize(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
x = np.array([1,2,3,4,5,6])
y = x.reshape(2,3)
x

array([1, 2, 3, 4, 5, 6])

In [96]:
y

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
from random import randint

In [113]:
some_number = randint(1,3)
x = np.arange(5 * some_number)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
y = x.reshape(5,-1)
y

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [115]:
y = x.reshape(-1,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [116]:
y = x.reshape(4,-1) #raise value error

ValueError: cannot reshape array of size 10 into shape (4,newaxis)

### Indexing and slicing

In [117]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [118]:
x[2]

2

In [119]:
x[2:4]

array([2, 3])

In [120]:
x[::-1]

array([5, 4, 3, 2, 1, 0])

In [121]:
x[2:4] = 100 
x

array([  0,   1, 100, 100,   4,   5])

### Broadcasting vs copying

In [122]:
x = np.arange(6)

In [123]:
x_slice = x[2:4]
x_slice

array([2, 3])

In [124]:
x

array([0, 1, 2, 3, 4, 5])

In [125]:
x_slice[:] = 100 
x

array([  0,   1, 100, 100,   4,   5])

In [126]:
x = np.arange(6)
x_slice = x[2:4].copy()

x_slice[:] = 100
x

array([0, 1, 2, 3, 4, 5])

In [128]:
x_slice

array([100, 100])

### Two dimensional indexing and slicing

In [129]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
x[0]

array([1, 2, 3])

In [131]:
x[0][2]

3

In [132]:
x[0,2]

3

In [133]:
x[:, 0] #first column

array([1, 4, 7])

In [134]:
x[0:2, 1:]

array([[2, 3],
       [5, 6]])

### Boolean indexing

In [148]:
names = np.array(['Bob', 'Alice', 'Charles', 'Bob', 'Billie', 'Bob'])

data = np.random.randint(0,10, (6,3))
data

array([[5, 3, 0],
       [3, 4, 5],
       [0, 1, 7],
       [8, 1, 3],
       [6, 2, 0],
       [0, 1, 2]])

In [146]:
names == 'Bob'

array([ True, False, False,  True, False,  True])

In [149]:
data[names == 'Bob']

array([[5, 3, 0],
       [8, 1, 3],
       [0, 1, 2]])